name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  l10n:
    path: ../l10n
  commons_entities:
    path: ../commons_entities
  dependencies:
    path: ../dependencies

  dio_http2_adapter: ^2.0.0

dev_dependencies:

  # Code generator

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ">=1.1.1 < 2.3.2"
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

  # test
  mockito: ^5.3.2

  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.6.0
flutter:

