library dependencies;

export 'package:dartz/dartz.dart' hide State, id, Unit, Option, OpenFile;
export 'package:dio/dio.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:json_annotation/json_annotation.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:internet_connection_checker/internet_connection_checker.dart';
export 'package:formz/formz.dart';
export 'package:equatable/equatable.dart';
export 'package:get_it/get_it.dart';
export 'package:hive/hive.dart';
export 'package:hive/src/hive_impl.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:package_info_plus/package_info_plus.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:path_provider/path_provider.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:flutter_cache_manager/flutter_cache_manager.dart';
export 'package:auto_route/auto_route.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:shimmer/shimmer.dart';
export 'package:flutter_html/flutter_html.dart' hide HtmlParser, Marker;
export 'dart:ui';
export 'package:lottie/lottie.dart';
export 'package:html/parser.dart';
export 'package:better_player/better_player.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:sms_autofill/sms_autofill.dart';
export 'package:firebase_crashlytics/firebase_crashlytics.dart';
export 'package:qr_code_scanner/qr_code_scanner.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:batch_flutter/batch.dart';
export 'package:batch_flutter/batch_inbox.dart';
export 'package:batch_flutter/batch_messaging.dart';
export 'package:batch_flutter/batch_push.dart';
export 'package:batch_flutter/batch_user.dart';
export 'package:share_plus/share_plus.dart';
export 'package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart';
export 'package:flutter_inappwebview/flutter_inappwebview.dart';
export 'package:intl_phone_number_input/intl_phone_number_input.dart';

///export 'package:qr_flutter/qr_flutter.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';
export 'package:open_file/open_file.dart';
export 'package:local_auth/local_auth.dart';
export 'package:google_fonts/google_fonts.dart';

export 'package:flutter_login_facebook/flutter_login_facebook.dart';
export 'package:sign_in_with_apple/sign_in_with_apple.dart';
export 'package:google_sign_in/google_sign_in.dart';
