name: auth
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

    # Infrastructure Packages
  core:
    path: ../../../infrastructures/core
  dependencies:
    path: ../../../infrastructures/dependencies
  l10n:
    path: ../../../infrastructures/l10n
  preferences:
    path: ../../../infrastructures/preferences
  commons_entities:
    path: ../../../infrastructures/commons_entities
  commons_components:
    path: ../../../infrastructures/commons_components

dev_dependencies:

  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  freezed: ">=1.1.1 < 2.3.2"
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  # test
  mockito: ^5.3.2

  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
