name: technique_mobile_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  flutter_localizations:
    sdk: flutter
  provider:
  auto_route:

      # Infrastructure Packages
  commons_components:
    path: ../infrastructures/commons_components
  commons_entities:
    path: ../infrastructures/commons_entities
  core:
    path: ../infrastructures/core
  dependencies:
    path: ../infrastructures/dependencies
  l10n:
    path: ../infrastructures/l10n
  preferences:
    path: ../infrastructures/preferences


      #  Core Features Packages
  auth:
    path: ../features/core_features/auth



  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generator
  flutter_lints: ^2.0.1
  # Route generator
  auto_route_generator:
  flutter_flavorizr: ^2.1.5
  # Code generator from models (to json and from json)
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.6.0
  build_runner: ^2.4.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/cfg/
     - assets/vectors/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
